### PR TITLE
Upload nightly AppImage to Transfer.sh

### PR DESCRIPTION
**Pull request by Symbian9**

### CODE REVIEW

**Comment by Symbian9** [comment]
@probonopd, could you take a look why its upload failed?

```
...
$ zip -v Astree-nightly.zip Astree*.AppImage*
  adding: Astree-269173c-x86_64.AppImage .	(in=20303912) (out=19896527) (deflated 2%)
  adding: Astree-269173c-x86_64.AppImage.zsync 	(in=69636) (out=69639) (deflated 0%)
total bytes=20373548, compressed=19966166 -> 2% savings
$ curl --upload-file Astree-nightly.zip https://transfer.sh/Astree-nightly.zip
Could not save metadata
Could not save metadata
Could not save metadata
...
```

**Comment by probonopd** [comment]
I think transfer.sh has issues (again). Better find another host...

**Comment by probonopd** [comment]
Maybe upload to GitHub Releases instead?
https://github.com/probonopd/uploadtool can be used to do it.

**Comment by edeforas** [comment]
Thanks, will try.

Le ven. 31 juil. 2020 à 16:49, probonopd <notifications@github.com> a
écrit :

**Comment by Symbian9** [comment]
> I think transfer.sh has issues (again). Better find another host...

Actual owners of `transfer.sh` fixed it on my request in June: 

- https://twitter.com/storjproject/status/1268663869469274113

**Comment by probonopd** [comment]
Just found transfersh.com which seems to have much better performance but works the same otherwise...

**Pull request merged**
